import { MDCSnackbarFoundation } from '@material/snackbar';

import {
  addClass,
  deregisterInteractionHandler,
  deregisterInteractionHandlerAny,
  registerInteractionHandler,
  registerInteractionHandlerAny,
  removeClass,
  setActionAriaHidden,
  setActionText,
  setAriaHidden,
  setFocus,
  setMessageText,
  unsetActionAriaHidden,
  unsetAriaHidden,
  visibilityIsHidden,
} from './adapter-utilities';

export default ({
  elementActionButton,
  elementSnackbar,
  notifyHide,
  notifyShow,
  updateActionButtonAriaHidden,
  updateActionButtonText,
  updateClassNames,
  updateSnackbarAriaHidden,
  updateSnackbarText,
}) => new MDCSnackbarFoundation({
  addClass: addClass(updateClassNames),
  deregisterActionClickHandler: deregisterInteractionHandler(elementActionButton, 'click'),
  // handler => deregisterInteractionHandler(elementActionButton)('click', handler),
  deregisterCapturedBlurHandler: deregisterInteractionHandler(elementActionButton, 'blur'),
  // handler => deregisterInteractionHandler(elementActionButton)('blur', handler),

  deregisterCapturedInteractionHandler: deregisterInteractionHandlerAny(document.body),
  // (type, handler) => deregisterInteractionHandler(document.body, type)(handler),

  deregisterTransitionEndHandler: deregisterInteractionHandler(elementSnackbar, 'transitionend'),
  // handler => deregisterInteractionHandler(elementSnackbar)('transitionend', handler),
  deregisterVisibilityChangeHandler: deregisterInteractionHandler(document, 'visibilitychange'),
  // handler => deregisterInteractionHandler(document)('visibilitychange', handler),
  notifyHide,
  notifyShow,
  registerActionClickHandler: registerInteractionHandler(elementActionButton, 'click'),
  // handler => registerInteractionHandler(elementActionButton)('click', handler),
  registerCapturedBlurHandler: registerInteractionHandler(elementActionButton, 'blur'),
  // handler => registerInteractionHandler(elementActionButton)('blur', handler),

  registerCapturedInteractionHandler: registerInteractionHandlerAny(document.body),
  // (type, handler) => registerInteractionHandler(document.body, type)(handler),

  registerTransitionEndHandler: registerInteractionHandler(elementSnackbar, 'transitionend'),
  // handler => registerInteractionHandler(elementSnackbar)('transitionend', handler),
  registerVisibilityChangeHandler: registerInteractionHandler(document, 'visibilitychange'),
  // handler => registerInteractionHandler(document)('visibilitychange', handler),
  removeClass: removeClass(updateClassNames),
  setActionAriaHidden: setActionAriaHidden(updateActionButtonAriaHidden),
  setActionText: setActionText(updateActionButtonText),
  setAriaHidden: setAriaHidden(updateSnackbarAriaHidden),
  setFocus: setFocus(elementActionButton),
  setMessageText: setMessageText(updateSnackbarText),
  unsetActionAriaHidden: unsetActionAriaHidden(updateActionButtonAriaHidden),
  unsetAriaHidden: unsetAriaHidden(updateSnackbarAriaHidden),
  visibilityIsHidden: visibilityIsHidden(),
});
